name: VanishNP
main: VanishNP\Loader
version: 1.1.0
api: 3.0.0-ALPHA7
authors:
 - iksaku
 - jasonwynn10
description: "Special plugin that allow to Vanish player without using Effects"
softdepend:
  - EssentialsPE
permissions:
  vanish:
    default: op
    description: "Get vanished!"
    chidren:
      vanish.other:
        default: op
        dewsription: "Vanish other players!"